language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Gbx8jbRXgkzps0e370lbVbSa0OGFy1nLPerYh+2AWmf4ahsh6q00RIyKEX6WM00Fum46uZGOQ8vYcEBEoQkYvUXWuk+ATG1W8a2ylSE0oGALHnYANv8SLAb+jar5NOvpOeQ8qhYXkeiLrHHsHRV28ppEDwnJZhrF2fi70nwDbNVTMP9oPJTvDSG2xo9joS3HtR8pl6M+zd+6ivdEUndE/uWc8KKdORZDFiH2Gk7PxHYWKMlP9rC+ImsGFRmtZiYtFDUbqiPfYvUBN0VaMWmZ5F0hd4XayijwjwNHN+54waWShZSyQ84RAfUg/bZO52tOzYGgEyAI7o6J2Y9JVYbfPGuKuFWlPZEjr0YABHeXRIjot2lI8gptVzG5KMHnGzDbymVgABS85rCblf96c9yHpoqL9Wiftua+irr90gJdJ140Dd4p2rVJzmuZ0FQJIehrKXaK+XDFsaxksI6hb65Lca+VZdHzIdZ8LXo0PHZRfRvPnJNe7C8jX8MplTnee0pJV6g23wlJBsCONuD3Ub3iNGgJt7Z84kLyfxL5nFKslBf2cyhA1Z2kjLiWmlQnT202h0xcNdbIsh9nNW2zUbcqD1HM/lyYNwmu2dVcNNJdK7LR+hq5hFlI7IbNNa/TWF0AgXUBMy0tIWFAHbcFWeZrcmOOnQ0cMHfoNVW2o8Y6o28="
env:
  secure: "OoqfGakyh8sAyi8tbasfbEmDjg4KTJuz8J7U1SxXGvQj+wKMFaOtX+OQ9yrTUxF8m22mR0go2mda8cpFaHfSeu/VwlX8D/3WJrIIwS8l1ZUYwBoEctp4qWnlWnG4GC+XY4GzELrxArG3cx4LXL/n4rwOWTQPGiEqTfK+RtR7wnoMJ37xu3UzMfZ5oUA0KTDrHXsiubLBgwynmJPJOobU7T7DvlbUWD+cyJlv3j/Y6YkoTVWjJseiVCdV6hhW+rb+nngjMVbqsGl/F5CnOXG21FYMD8oR8HFv/cwx65vbu8MMT7V+dZngKmhi5n52wE2LSPcSkU/I+GDN/iHen1OPiuZvptAAyNyvvL1PoTrzmPSxBTe1rCGe8rApuQ0rO/SaIEYpj25l34L9n4ttZAHvAUZ/0f4/Pw87Lbbt3gdpgCqTEdsS0F1+EAKsQPG378kR4hOMcoIONQA2uq27bw2mmE6goUwyIjo2s9OOfX1ZpJ62PHtyeDa0iTIAl9NX7WD/hQ9Hv9zM1/ZwV71lcs2+TAlteCzs/PLH6tphBBY7S+PTbOKWSJ2TeovdqnmJefoPDoARx3NY7hpnYhc4XryvtSqnJfW2Rj1dDOfhnvPiAIbwNIeWLZeSbCdbSEBjIcZ7p5YtLTGKmEiqFR8paS55Qgj8RGy7JY6WXxBYGBF/oLY="
